src/accessories/simplicam.js
src/index.js
src/simplisafe.js

Initial Support for Camera Motion & Doorbell

---

src/accessories/simplicam.js

Camera EventListener Scoping Fixes

---

src/simplisafe.js

Camera Callbacks Don't Receive Disconnect

---

src/accessories/coDetector.js
src/index.js

Support for CO Detector

---

src/accessories/simplicam.js

Support 1080p Streams

---

src/accessories/simplicam.js

ffmpegPath Should Use Default if Not Specified

---

src/accessories/simplicam.js

Babel Compilation Namespace Error With ffmpeg Import

---

src/accessories/simplicam.js

Handle Snapshots When Motion Triggered During Alarm Deactivation

---

README.md
src/accessories/motionSensor.js
src/index.js
src/simplisafe.js

Support motion sensor events when sensor is set to "Silent Alarm" or "Alarm" in SimpliSafe device settings
Addresses #19 & #52

Motion Sensor Support

---

src/accessories/alarm.js
src/accessories/coDetector.js
src/accessories/doorLock.js
src/accessories/entrySensor.js
src/accessories/freezeSensor.js
src/accessories/motionSensor.js
src/accessories/simplicam.js
src/accessories/smokeDetector.js
src/accessories/waterSensor.js
src/simplisafe.js

This is to reduce lag and number of API calls.
Requires some testing

Lag and API optimization

---

README.md
src/accessories/alarm.js
src/accessories/coDetector.js
src/accessories/doorLock.js
src/accessories/entrySensor.js
src/accessories/freezeSensor.js
src/accessories/simplicam.js
src/accessories/smokeDetector.js
src/accessories/unreachableAccessory.js
src/accessories/waterSensor.js
src/index.js
src/simplisafe.js

- Support for multi factor authentication
- Support to recover 403 rate limit errors

Improved auth support

---

README.md
config.schema.json

Continuation of #62, updated for new config settings and updated README

Updated Config Schema + README

---

src/accessories/motionSensor.js

data May Be Empty on subscribeToEvents

---

src/accessories/alarm.js

Retry setting alarm state when SS api is busy

---

src/accessories/simplicam.js

Camera should gracefully handle rate limit errors

---

src/accessories/simplicam.js
src/index.js

Camera initialization should ignore accessory caching

---

src/index.js
src/simplisafe.js

Plugin should respect Homebridge storage path

---

src/accessories/alarm.js

Allow for retry on GatewayTimeout errors

---

src/simplisafe.js

Improved sensorRefresh logging

---

src/accessories/alarm.js

Initialize nRetries variable

---

src/accessories/simplicam.js

Incorrect parsing of ffmpeg options

---

src/accessories/alarm.js

nSocketConnectFailures needs to be initialized

---

CHANGELOG.md
src/accessories/alarm.js
src/accessories/coDetector.js
src/accessories/doorLock.js
src/accessories/entrySensor.js
src/accessories/freezeSensor.js
src/accessories/motionSensor.js
src/accessories/simplicam.js
src/accessories/smokeDetector.js
src/accessories/unreachableAccessory.js
src/accessories/waterSensor.js

Fix broken identify function

---

src/accessories/alarm.js
src/simplisafe.js

Allow alarms to listen for events from door locks

---

src/accessories/simplicam.js

Motion event sensorSerial is no longer UUID

---

src/accessories/doorLock.js

Locks can show incorrect initial state on startup

---

src/accessories/alarm.js
src/accessories/doorLock.js

Set targetState before currentState to improve notifications

---

src/accessories/alarm.js
src/accessories/coDetector.js
src/accessories/doorLock.js
src/accessories/entrySensor.js
src/accessories/freezeSensor.js
src/accessories/motionSensor.js
src/accessories/simplicam.js
src/accessories/smokeDetector.js
src/accessories/waterSensor.js

Compatibility with Homebridge 1.3.x

---

src/simplisafe.js

Typo: refreshing
